version: '3.8'

services:
  app:
    container_name: acsp-backend
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - app:/usr/src/app/
    environment:
      - DB_PASSWORD=1245emer
    networks:
      - cloud

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    volumes:
      - ./postgres:/data/db
    ports:
      - 5432:5432

  redis:
    image: redis-image
    container_name: redis_db
    networks:
      - cloud
    ports:
      - "6380:6380"
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  app:
  postgres:
  redis:

networks:
  cloud:
    driver: bridge
